# Generated by Django 3.2.12 on 2024-02-06 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategorijaLijeka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='raspolozenje',
            name='user',
        ),
        migrations.AddField(
            model_name='korisnik',
            name='lijekovi',
            field=models.ManyToManyField(to='main.Lijekovi'),
        ),
        migrations.AddField(
            model_name='raspolozenje',
            name='korisnik',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lijekovi',
            name='kategorija',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.kategorijalijeka'),
        ),
    ]
