# Generated by Django 3.2.12 on 2024-02-07 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20240206_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lijekovi',
            name='user',
        ),
        migrations.DeleteModel(
            name='Korisnik',
        ),
    ]
