# Generated by Django 3.2.12 on 2024-02-07 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20240207_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='KorisnikLijek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lijek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lijekovi')),
            ],
            options={
                'unique_together': {('korisnik', 'lijek')},
            },
        ),
    ]
